version: '3.1'

services:
  reverseproxy:
    image: bynarlogic/reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - verbosity_frontend
    restart:  always
  verbosity_backend:
    image: bynarlogic/verbosity_backend
    ports:
      - "4567:4567"
    command: rackup --host 0.0.0.0 -p 4567
    restart: always
  verbosity_frontend:
    image: bynarlogic/verbosity_frontend
    restart: always
