version: '3.1'

services:
  verbosity_backend:
    image: bynarlogic/verbosity_backend
    ports:
      - "4567:4567"
    command: rackup --host 0.0.0.0 -p 4567
    restart: always
  verbosity_frontend:
    image: bynarlogic/verbosity_frontend
    environment:
      - REACT_APP_HOST=refactorednoise.io
    ports:
      - "3000:3000"
